name: Publish GitHub Release
description: Create a new Release based on the release notes from the associated pull request
inputs:
  version:
    description: The version for this release
    required: true
  add-major-minor-tags:
    description: Add a Major and a Major.Minor tag
    required: false
    default: "false"
outputs:
  release-html-url:
    description: The url for the Release page created by this action
    value: ${{ steps.publish-release.outputs.release-html-url }}
  release-notes:
    description: The release notes
    value: ${{ steps.publish-release.outputs.release-notes }}
runs:
  using: composite
  steps:
    - name: Publish GitHub Release
      id: publish-release
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -Version '${{ inputs.version }}' -AddMajorMinorTags '${{ inputs.add-major-minor-tags }}''
      env:
        GITHUB_TOKEN: ${{ github.token }}
